---
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Thomas Rabensteiner

jobtitle: "Lecturer in Economics, University of Greenwich"
address: "Old Royal Naval College, Park Row, London SE10 9LS"
fontawesome: yes
email: t.rabensteiner@gre.ac.uk
# github: svmiller
twitter: thomsiaae
#osf: "Enter 5 digit osf string here"
#phone: "+44 77 3229 1862"
web: thomasrabensteiner.com
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Academic positions

\vspace{2 mm}
\hrule

**University of Greenwich**, London, UK \hfill Since Jan 2023

*Lecturer in Economics*


# Education
\vspace{2 mm}
\hrule

**University of Greenwich**, London, UK \hfill Jan 2020 - Nov 2023

*PhD in Economics*

  - Thesis title: An analysis of changes in European employment and wage structures
  - Supervisors: Dr Alexander Guschanski, Prof Özlem Onaran and Dr Rafael Wildauer

**University of Greenwich**
\hfill Sep 2018 - Nov 2019

*MSc in Economics*

**University of Graz**, Austria
\hfill Oct 2012 - Mar 2017

*BA in Economics*

**University of Istanbul**, Turkey
\hfill Sep 2014 - Feb 2015

*Exchange*

# Working papers
\vspace{2 mm}
\hrule

**[Autonomy and wage divergence: evidence from European Survey data](https://gala.gre.ac.uk/id/eprint/37925/25/37925_RABENSTEINER_Autonomy_and_wage_divergence_Evidence_from_European_survey_data.pdf)**<br>
with Alexander Guschanski

**[A progressive excess profit tax for the European Union](https://gala.gre.ac.uk/id/eprint/45941/7/45941_TIPPET_A_progressive%20_excess_profit_tax_for_the_European_Union.pdf)**<br>
with Ines Heck and Ben Tippet

\vspace{2 mm}


# Policy briefs
\vspace{2 mm}
\hrule
**[Business case for a New Deal for Workers: What is good for Workers is good for the Economy](https://gala.gre.ac.uk/id/eprint/47309/3/47309_ONARAN_Business_case_for_a_New_Deal_for_workers_What_is_good_for_workers_is_good_for_the_economy.pdf)**<br>
with Özlem Onaran and Alexander Guschanski


\vspace{2 mm}


# In progress
\vspace{2 mm}
\hrule
**Do recessions accelerate routine-biased technological change in Western Europe?**
with Alexander Guschanski

**The rise of the supervisory wage premium**
with Alexander Guschanski


\vspace{2 mm}

# Teaching 
\vspace{2 mm}
\hrule

**University of Greenwich**
\hfill Sep 2020 - present

*Module leader*

- Applied Data Analysis (from Sep 2024)
- Intermediate Macroeconomics (2022/23 - today)

*Tutorial leader*

- Research Design (2022/23)
- Macroeconomics (2020/21 and 2021/22)
- Statistics for Economics and Finance (2021/22)
- Macroeconomics (MSc) (2022/23)
- Introduction to Macroeconomics for Business (2022/23)


*Dissertation supervision*

- MSc Economics (2022/23- today)

\vspace{2 mm}

# Skills
\vspace{2 mm}
\hrule

**Languages**: German (native), English (proficient), French (intermediate), Spanish (intermediate)

**IT skills**: Stata, R, Python, LaTeX, Markdown, MS Office

\vspace{2 mm}

# Invited presentations
\vspace{2 mm}
\hrule

- Post-Keynesian Economic Society Summer School 2024, Topic: Recent trends in the wage distribution
- Post-Keynesian Economic Society Summer School 2023, Topic: Income inequality and the cost of living crisis


\vspace{2 mm}

# Presentations
\vspace{2 mm}
\hrule

*2023*

Luxembourg Income and Wealth Study Conference, Gdansk University of Technology, Gdansk, September 2023
EAEPE Conference, Leeds, September 2023
Regulating for Decent Work Conference, International Labour Organization, Geneva, July 2023
Annual Conference of the Association for Heterodox Economics, Cambridge, UK, June 2023 
Post-Keynesian Economic Society PhD Conference, London, May 2023
Allied Social Science Associations (ASSA) Annual Meeting, New Orleans, LA, January 2023


*2022*

Forum for Macroeconomics and Macroeconomic Policies Conference, Young Economists Conference, EAEPE Conference, Post-Keynesian Economic Society PhD Conference, PEGFA Seminar at University of Greenwich, Post-Keynesian Economic Society Research Workshop

*2021*

Forum for Macroeconomics and Macroeconomic Policies Conference, Barcelona Graduate School in Economics Summer School in Labour Economics, London Political Economy Network PhD Conference, Post-Keynesian Economic Society PhD Conference


# Awards and distinctions
\vspace{2 mm}
\hrule

- Mark Hayes Prize, 2022
- Three Minute Thesis 2022 Winner, University of Greenwich 
- Three Minute Thesis 2022 UK Semi-Finalist
- VC Scholarship, University of Greenwich
- Austrian Chamber of Labour Scholarship for Master's studies abroad, 2018
- Merit Scholarship, University of Graz, 2016

\hrule

